/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 健康检查 */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Prometheus 指标（内部可观测） */
        get: operations["metrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 任务列表 */
        get: operations["listTasksV2"];
        put?: never;
        /** 创建巡检任务（同名同 checksum 复用；同名不同 checksum 冲突） */
        post: operations["createTaskV2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 任务摘要（不含全量规则结果） */
        get: operations["getTaskV2"];
        put?: never;
        post?: never;
        /** 删除任务（级联删除 uploads/ 与 output/ 现场数据） */
        delete: operations["deleteTaskV2"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/tasks/{task_id}/rerun": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 增量重跑（全部或指定规则） */
        post: operations["rerunTaskV2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/tasks/{task_id}/rebuild": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 重建重跑（全量或强制重建解压的增量） */
        post: operations["rebuildTaskV2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/tasks/{task_id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 巡检报告（HTML 在线预览） */
        get: operations["getReportV2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/tasks/{task_id}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 任务执行日志 */
        get: operations["getTaskLogsV2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/tasks/{task_id}/system": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 系统摘要与规则状态列表 */
        get: operations["getSystemV2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/tasks/{task_id}/rules/{rule_code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 单规则完整结果 */
        get: operations["getRuleResultV2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/tasks/{task_id}/rules/{rule_code}/kpi/records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 分页查询 KPI 原始记录 */
        get: operations["listKpiRecordsV2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 全局巡检概览 */
        get: operations["getOverviewV2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/inspectors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 已注册规则元数据（只读） */
        get: operations["listInspectorsV2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/dicts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 全部预制数据字典 */
        get: operations["listDictsV2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/dicts/{dict_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 维护字典项（纯内部开放） */
        put: operations["updateDictV2"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v3/kpi/resource-metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 分页查询基础指标 */
        get: operations["listKpiResourceMetricsV3"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v3/kpi/resource-metrics/classification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 批量分类 KPI 指标 */
        put: operations["classifyKpiResourceMetricsV3"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v3/kpi/resource-metrics/classification-audits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 分页查询 KPI 分类审计 */
        get: operations["listKpiClassificationAuditsV3"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v3/tasks/{task_id}/kpi/catalog-snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 读取任务 KPI 配置快照 */
        get: operations["getKpiCatalogSnapshotV3"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        TaskStatus: "pending" | "running" | "completed" | "failed";
        /** @enum {string} */
        RuleStatus: "pass" | "warn" | "fail" | "error" | "skip";
        /** @enum {string} */
        Severity: "low" | "medium" | "high" | "critical";
        /**
         * @description P0 数据准备 / P1 基础检查 / P2 综合分析
         * @enum {integer}
         */
        Priority: 0 | 1 | 2;
        /** @enum {string} */
        RuleCategory: "log" | "kpi" | "traffic" | "alarm" | "config" | "resource" | "other";
        /** @enum {string} */
        TaskMode: "online" | "local";
        /** @enum {string} */
        TaskTrigger: "api" | "cli" | "rerun";
        Summary: {
            total: number;
            pass: number;
            warn: number;
            fail: number;
            error: number;
            skip: number;
        };
        TaskStats: components["schemas"]["Summary"] & {
            systems?: number;
        };
        Metric: {
            /** @description 契约级稳定标识，跨任务/系统不可变 */
            key: string;
            label: string;
            value: number | string;
            unit?: string;
            threshold?: {
                min?: number;
                max?: number;
            };
            baseline?: number | string;
            /** @description 趋势图数据 */
            series?: {
                /** @description 时间点或序号 */
                t?: string;
                v?: number | string;
            }[];
        };
        Finding: {
            finding_id: string;
            title: string;
            severity: components["schemas"]["Severity"];
            /** @description 结论来源文件（可定位原始数据） */
            source_file?: string;
            /** @description 证据片段（默认截断 2KB） */
            evidence?: string;
            details?: string;
            recommendation?: string;
            metrics?: components["schemas"]["Metric"][];
        };
        RuleResult: {
            code: string;
            name: string;
            category: components["schemas"]["RuleCategory"];
            priority: components["schemas"]["Priority"];
            execution_order: number;
            status: components["schemas"]["RuleStatus"];
            severity: components["schemas"]["Severity"];
            summary?: string;
            /** @description status=skip 时必填 */
            skip_reason?: string;
            /** Format: date-time */
            executed_at?: string;
            duration_ms?: number;
            metrics?: components["schemas"]["Metric"][];
            findings?: components["schemas"]["Finding"][];
            metadata?: {
                [key: string]: unknown;
            };
        };
        SystemInspection: {
            package_file: string;
            package_checksum?: string;
            version?: string;
            /** @enum {string} */
            status: "completed" | "failed";
            summary: components["schemas"]["Summary"];
            rules: components["schemas"]["RuleResult"][];
            customer?: {
                [key: string]: unknown;
            };
        };
        InspectionTask: {
            task_id: string;
            name: string;
            mode: components["schemas"]["TaskMode"];
            status: components["schemas"]["TaskStatus"];
            trigger: components["schemas"]["TaskTrigger"];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            completed_at?: string;
            stats: components["schemas"]["TaskStats"];
            system?: components["schemas"]["SystemInspection"];
        };
        TaskCreated: {
            task_id: string;
        };
        TaskSummary: components["schemas"]["InspectionTask"] & {
            system?: unknown;
            /** @description 上传时选择的省份字典编码（可选） */
            customer_province?: string;
            /** @description 上传时选择的运营商字典编码（可选） */
            customer_operator?: string;
            /** @description 上传时选择的产品形态字典编码（可选） */
            customer_product?: string;
            /** @description 上传时选择的版本字典编码（可选） */
            customer_version?: string;
        };
        TaskListResponse: {
            items: components["schemas"]["TaskSummary"][];
            total: number;
            page: number;
            page_size: number;
        };
        OverviewSummary: {
            /** @description 任务总数 */
            task_count: number;
            /** @description 注册规则总数（包含 hidden 内部规则） */
            registered_rule_count: number;
            /** @description 全部任务的规则结果总数 */
            rule_result_count: number;
            /** @description 全部任务的发现问题总数（按 Finding 记录数，不去重） */
            finding_count: number;
            status_counts: components["schemas"]["Summary"];
        };
        RerunRequest: {
            /** @description 不填表示重跑该任务全部规则 */
            rule_codes?: string[];
        };
        /** @enum {string} */
        RebuildModeV2: "full" | "incremental";
        RebuildRequestV2: {
            mode: components["schemas"]["RebuildModeV2"];
            /** @description 破坏性重建确认；必须为 true。 */
            confirmed: boolean;
            /** @description 增量目标普通规则；全量请求必须省略或为空。 */
            rule_codes?: string[];
            /**
             * @default ui
             * @enum {string}
             */
            trigger_source: "ui" | "api";
        };
        LogEntry: {
            /** Format: date-time */
            ts: string;
            level: string;
            message: string;
            rule_code?: string;
            detail?: {
                [key: string]: unknown;
            };
        };
        TaskLogs: {
            task_id: string;
            entries: components["schemas"]["LogEntry"][];
        };
        InspectorInfo: {
            code: string;
            name: string;
            category: components["schemas"]["RuleCategory"];
            severity: components["schemas"]["Severity"];
            priority: components["schemas"]["Priority"];
            rule_version: string;
            hidden: boolean;
            description?: string;
            recommendation?: string;
            /** @description 匹配任务目录内相对路径的正则 */
            source_patterns: string[];
            outputs: {
                metrics?: {
                    key?: string;
                    label?: string;
                    unit?: string;
                    /** @enum {string} */
                    type?: "number" | "string" | "trend";
                }[];
            };
            params?: {
                key?: string;
                label?: string;
                default?: string;
            }[];
        };
        DictItem: {
            /** @description 编码，仅小写字母/数字/下划线 */
            code: string;
            name: string;
        };
        DictsResponse: {
            province: components["schemas"]["DictItem"][];
            operator: components["schemas"]["DictItem"][];
            product: components["schemas"]["DictItem"][];
            version: components["schemas"]["DictItem"][];
        };
        DictUpdateRequest: {
            code: string;
            name: string;
        };
        Error: {
            /**
             * @description 错误码（新增时同步契约与实现）
             * @enum {string}
             */
            code: "invalid_package" | "package_too_large" | "invalid_dict" | "bad_request" | "unknown_rule" | "not_found" | "internal";
            message: string;
            detail?: {
                [key: string]: unknown;
            };
        };
        /** @enum {string} */
        TaskStatusV2: "pending" | "running" | "completed" | "failed";
        /** @enum {string} */
        RuleStatusV2: "pass" | "warn" | "fail" | "error" | "skip";
        /** @enum {string} */
        SeverityV2: "low" | "medium" | "high" | "critical";
        /**
         * @description P0 数据准备 / P1 基础检查 / P2 综合分析
         * @enum {integer}
         */
        PriorityV2: 0 | 1 | 2;
        /** @enum {string} */
        RuleCategoryV2: "log" | "kpi" | "traffic" | "alarm" | "config" | "resource" | "other";
        /** @enum {string} */
        TaskModeV2: "online" | "local";
        /** @enum {string} */
        TaskTriggerV2: "api" | "cli" | "rerun";
        SummaryV2: {
            total: number;
            pass: number;
            warn: number;
            fail: number;
            error: number;
            skip: number;
        };
        TaskStatsV2: components["schemas"]["SummaryV2"] & {
            systems?: number;
        };
        MetricV2: {
            /** @description 契约级稳定标识，跨任务/系统不可变 */
            key: string;
            label: string;
            value: number | string;
            unit?: string;
            threshold?: {
                min?: number;
                max?: number;
            };
            baseline?: number | string;
            /** @description 趋势图数据 */
            series?: {
                /** @description 时间点或序号 */
                t?: string;
                v?: number | string;
            }[];
        };
        FindingV2: {
            finding_id: string;
            title: string;
            severity: components["schemas"]["SeverityV2"];
            /** @description 结论来源文件（可定位原始数据） */
            source_file?: string;
            /** @description 证据片段（默认截断 2KB） */
            evidence?: string;
            details?: string;
            recommendation?: string;
            metrics?: components["schemas"]["MetricV2"][];
        };
        RuleResultV2: {
            code: string;
            name: string;
            category: components["schemas"]["RuleCategoryV2"];
            priority: components["schemas"]["PriorityV2"];
            execution_order: number;
            status: components["schemas"]["RuleStatusV2"];
            severity: components["schemas"]["SeverityV2"];
            summary?: string;
            /** @description status=skip 时必填 */
            skip_reason?: string;
            /** Format: date-time */
            executed_at?: string;
            duration_ms?: number;
            metrics?: components["schemas"]["MetricV2"][];
            findings?: components["schemas"]["FindingV2"][];
            metadata?: {
                [key: string]: unknown;
            };
        };
        SystemInspectionV2: {
            package_file: string;
            package_checksum?: string;
            version?: string;
            /** @enum {string} */
            status: "completed" | "failed";
            summary: components["schemas"]["SummaryV2"];
            rules: components["schemas"]["RuleResultV2"][];
            customer?: {
                [key: string]: unknown;
            };
        };
        /** @enum {string} */
        PreparationStatusV2: "pass" | "warn" | "fail" | "skip" | "error";
        /** @enum {string} */
        PreparationIssueTypeV2: "conflict" | "duplicate" | "skipped" | "failed" | "rejected";
        PreparationIssueV2: {
            type: components["schemas"]["PreparationIssueTypeV2"];
            source?: string | null;
            target?: string | null;
            reason: string;
            path_length?: number | null;
            path_limit?: number | null;
        };
        PreparationItemV2: {
            /** @example pkg.extract.kpi */
            code: string;
            /** @example KPI 分类解压 */
            name: string;
            /** @example kpi */
            category: string;
            status: components["schemas"]["PreparationStatusV2"];
            summary: string;
            duration_ms?: number | null;
            extracted_count: number;
            total_count: number;
            issues: components["schemas"]["PreparationIssueV2"][];
        };
        DataPreparationV2: {
            status: components["schemas"]["PreparationStatusV2"];
            items: components["schemas"]["PreparationItemV2"][];
            total: number;
            success_count: number;
            warning_count: number;
            failure_count: number;
            skip_count: number;
        };
        InspectionTaskV2: {
            task_id: string;
            name: string;
            mode: components["schemas"]["TaskModeV2"];
            status: components["schemas"]["TaskStatusV2"];
            trigger: components["schemas"]["TaskTriggerV2"];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            completed_at?: string;
            stats: components["schemas"]["TaskStatsV2"];
            preparation?: components["schemas"]["DataPreparationV2"] | null;
            system?: components["schemas"]["SystemInspectionV2"];
        };
        TaskCreatedV2: {
            task_id: string;
        };
        TaskSummaryV2: components["schemas"]["InspectionTaskV2"] & {
            system?: unknown;
            /** @description 上传时选择的省份字典编码（可选） */
            customer_province?: string;
            /** @description 上传时选择的运营商字典编码（可选） */
            customer_operator?: string;
            /** @description 上传时选择的产品形态字典编码（可选） */
            customer_product?: string;
            /** @description 上传时选择的版本字典编码（可选） */
            customer_version?: string;
        };
        TaskListResponseV2: {
            items: components["schemas"]["TaskSummaryV2"][];
            total: number;
            page: number;
            page_size: number;
        };
        OverviewSummaryV2: {
            /** @description 任务总数 */
            task_count: number;
            /** @description 注册规则总数（包含 hidden 内部规则） */
            registered_rule_count: number;
            /** @description 全部任务的规则结果总数 */
            rule_result_count: number;
            /** @description 全部任务的发现问题总数（按 Finding 记录数，不去重） */
            finding_count: number;
            status_counts: components["schemas"]["SummaryV2"];
        };
        RerunRequestV2: {
            /** @description 不填表示重跑该任务全部规则 */
            rule_codes?: string[];
        };
        LogEntryV2: {
            /** Format: date-time */
            ts: string;
            level: string;
            message: string;
            rule_code?: string;
            detail?: {
                [key: string]: unknown;
            };
        };
        TaskLogsV2: {
            task_id: string;
            entries: components["schemas"]["LogEntryV2"][];
        };
        InspectorInfoV2: {
            code: string;
            name: string;
            category: components["schemas"]["RuleCategoryV2"];
            severity: components["schemas"]["SeverityV2"];
            priority: components["schemas"]["PriorityV2"];
            rule_version: string;
            hidden: boolean;
            description?: string;
            recommendation?: string;
            /** @description 匹配任务目录内相对路径的正则 */
            source_patterns: string[];
            outputs: {
                metrics?: {
                    key?: string;
                    label?: string;
                    unit?: string;
                    /** @enum {string} */
                    type?: "number" | "string" | "trend";
                }[];
            };
            params?: {
                key?: string;
                label?: string;
                default?: string;
            }[];
        };
        DictItemV2: {
            /** @description 编码，仅小写字母/数字/下划线 */
            code: string;
            name: string;
        };
        DictsResponseV2: {
            province: components["schemas"]["DictItemV2"][];
            operator: components["schemas"]["DictItemV2"][];
            product: components["schemas"]["DictItemV2"][];
            version: components["schemas"]["DictItemV2"][];
        };
        DictUpdateRequestV2: {
            code: string;
            name: string;
        };
        /** @description 任务删除失败错误（detail 携带重试上下文） */
        TaskDeleteErrorV2: components["schemas"]["ErrorV2"] & {
            detail?: components["schemas"]["TaskDeleteErrorDetailV2"];
        };
        TaskDeleteErrorDetailV2: {
            /** @description 任务标识，禁止修改。 */
            task_id: string;
            /** @description 删除涉及的现场相对位置。 */
            locations: string[];
            /** @description 删除失败的具体路径。 */
            failed_path: string;
            /** @description 可读失败原因。 */
            reason: string;
            /** @description 路径长度；仅路径限制相关错误返回。 */
            path_length?: number;
            /** @description 路径长度上限；仅路径限制相关错误返回。 */
            path_limit?: number;
        };
        /** @description 错误码（/api/v2 含包上传与损坏数据错误） */
        ErrorV2: {
            /**
             * @description 错误码（新增时同步契约与实现）
             * @enum {string}
             */
            code: "invalid_package" | "package_too_large" | "invalid_dict" | "bad_request" | "unknown_rule" | "not_found" | "internal" | "task_delete_failed" | "package_checksum_conflict" | "invalid_filename" | "invalid_resource_csv" | "resource_conflict" | "corrupt_data" | "validation_error" | "invalid_rebuild_request" | "task_busy" | "package_missing" | "kpi_snapshot_invalid";
            message: string;
            detail?: {
                [key: string]: unknown;
            };
        };
        /** @enum {string} */
        KpiDisplayStatusV2: "pass" | "warn" | "fail" | "neutral" | "unavailable";
        KpiRecordItemV2: {
            metric_key: string;
            metric_name_zh: string;
            source_file: string;
            line_number: number;
            period_minutes: number;
            /** Format: date-time */
            start_at: string;
            /** Format: date-time */
            end_at: string;
            value: number | string | null;
            status: components["schemas"]["KpiDisplayStatusV2"];
            errors: {
                [key: string]: unknown;
            }[];
        };
        KpiRecordPageV2: {
            total: number;
            page: number;
            page_size: number;
            items: components["schemas"]["KpiRecordItemV2"][];
        };
        KpiMetricDefinitionV2: {
            key: string;
            name_zh: string;
            name_en: string;
            aliases: {
                [key: string]: unknown;
            }[];
            /** @enum {string} */
            metric_type: "count" | "rate" | "capacity" | "latency" | "gauge";
            /** @enum {string} */
            semantic_group: "quality" | "traffic" | "capacity" | "latency" | "other";
            /** @enum {string} */
            display_role: "highlight" | "context" | "diagnostic" | "catalog";
            unit: string | null;
            /** @enum {string} */
            source_type: "raw" | "derived";
            aggregation: {
                [key: string]: unknown;
            };
            formula?: {
                [key: string]: unknown;
            } | null;
            description?: string | null;
        };
        KpiMetricResultV2: {
            key: string;
            main_value: number | string | null;
            value_available: boolean;
            unavailable_reason?: string | null;
            display_status: components["schemas"]["KpiDisplayStatusV2"];
            unit: string | null;
            aggregation: string;
            threshold?: {
                [key: string]: unknown;
            } | null;
            breach_count: number;
            series: {
                [key: string]: unknown;
            }[];
            source_files: string[];
            provenance: {
                [key: string]: unknown;
            };
        };
        KpiUnclassifiedMetricV2: {
            source_name: string;
            source_files: string[];
            record_count: number;
            sample_values: unknown[];
            reason: string;
        };
        KpiMetadataV2: {
            version: number;
            domain: string;
            metric_catalog: components["schemas"]["KpiMetricDefinitionV2"][];
            kpi_results: components["schemas"]["KpiMetricResultV2"][];
            unclassified_metrics: components["schemas"]["KpiUnclassifiedMetricV2"][];
            kpi_files: {
                [key: string]: unknown;
            }[];
        };
        /** @enum {string} */
        KpiResourceDomainV3: "unclassified" | "call" | "api" | "media";
        KpiResourceMetricV3: {
            key: string;
            resource_id: string;
            name_zh: string;
            name_en: string;
            domain: components["schemas"]["KpiResourceDomainV3"];
            missing_from_base: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        KpiResourceMetricPageV3: {
            items: components["schemas"]["KpiResourceMetricV3"][];
            total: number;
            page: number;
            page_size: number;
            base_data_version: string;
            classification_version: number;
            summary: {
                unclassified: number;
                call: number;
                api: number;
                media: number;
            };
        };
        KpiResourceClassificationRequestV3: {
            metric_keys: string[];
            /** @enum {string} */
            domain: "unclassified" | "call" | "api" | "media";
            operator: string;
        };
        KpiResourceClassificationResultV3: {
            classification_version: number;
            /** @enum {string} */
            domain: "unclassified" | "call" | "api" | "media";
            metric_keys: string[];
            audited_count: number;
        };
        KpiClassificationAuditV3: {
            id: number;
            metric_key: string;
            /** @enum {string} */
            operation: "classify" | "unclassify";
            operator: string;
            /** @enum {string} */
            from_domain: "unclassified" | "call" | "api" | "media";
            /** @enum {string} */
            to_domain: "unclassified" | "call" | "api" | "media";
            /** @enum {string} */
            result: "success";
            /** Format: date-time */
            operated_at: string;
        };
        KpiClassificationAuditPageV3: {
            items: components["schemas"]["KpiClassificationAuditV3"][];
            total: number;
            page: number;
            page_size: number;
        };
        KpiTaskCatalogSnapshotV3: {
            /** @enum {integer} */
            schema_version: 1;
            base_data_version: string;
            classification_version: number;
            /** Format: date-time */
            captured_at: string;
            metrics: {
                [key: string]: unknown;
            }[];
            rules: {
                [key: string]: unknown;
            };
        };
    };
    responses: {
        /** @description 请求错误 */
        Error400: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 资源不存在 */
        Error404: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 文件过大 */
        Error413: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 请求参数校验失败 */
        Error422: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorV2"];
            };
        };
        /** @description 服务器内部错误 */
        Error500: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorV2"];
            };
        };
    };
    parameters: {
        TaskId: string;
        RuleCode: string;
        Page: number;
        PageSize: number;
        KpiRecordPageSize: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 服务健康 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    metrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Prometheus 文本格式指标 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    listTasksV2: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                page_size?: components["parameters"]["PageSize"];
                status?: components["schemas"]["TaskStatusV2"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 任务摘要列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskListResponseV2"];
                };
            };
            422: components["responses"]["Error422"];
        };
    };
    createTaskV2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description 数据压缩包（zip/tar.gz，非空，默认上限 2GB）
                     */
                    package_file: string;
                    /** @description 任务名称（可选） */
                    name?: string;
                    /** @description 版本字典编码（可选） */
                    version?: string;
                    /** @description 省份字典编码（可选） */
                    province?: string;
                    /** @description 运营商字典编码（可选） */
                    operator?: string;
                    /** @description 产品形态字典编码（可选） */
                    product?: string;
                };
            };
        };
        responses: {
            /** @description 任务已创建，异步执行 */
            202: {
                headers: {
                    /** @example /api/v2/tasks/task-001 */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskCreatedV2"];
                };
            };
            400: components["responses"]["Error400"];
            /** @description 同名包但 checksum 不同 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorV2"];
                };
            };
            413: components["responses"]["Error413"];
        };
    };
    getTaskV2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 任务摘要 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InspectionTaskV2"];
                };
            };
            404: components["responses"]["Error404"];
        };
    };
    deleteTaskV2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已删除 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["Error404"];
            /** @description 任务正在排队或执行，禁止删除 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorV2"];
                };
            };
            /** @description 任务现场删除失败；任务记录与可恢复现场保持可见 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskDeleteErrorV2"];
                };
            };
        };
    };
    rerunTaskV2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RerunRequestV2"];
            };
        };
        responses: {
            /** @description 重跑任务已受理 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskCreatedV2"];
                };
            };
            404: components["responses"]["Error404"];
        };
    };
    rebuildTaskV2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RebuildRequestV2"];
            };
        };
        responses: {
            /** @description 重建任务已受理 */
            202: {
                headers: {
                    /** @description 任务详情地址 */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskCreatedV2"];
                };
            };
            /** @description 请求无效、未确认或规则无效 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorV2"];
                };
            };
            404: components["responses"]["Error404"];
            /** @description 任务忙、原始包缺失或增量快照无效 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorV2"];
                };
            };
        };
    };
    getReportV2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description HTML 报告 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
            404: components["responses"]["Error404"];
        };
    };
    getTaskLogsV2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 结构化执行日志 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskLogsV2"];
                };
            };
            404: components["responses"]["Error404"];
        };
    };
    getSystemV2: {
        parameters: {
            query?: {
                /** @description 为 true 时只返回规则状态摘要，清空 rules[].metadata/metrics/findings。 */
                exclude_details?: boolean;
            };
            header?: never;
            path: {
                task_id: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 系统巡检结果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemInspectionV2"];
                };
            };
            404: components["responses"]["Error404"];
        };
    };
    getRuleResultV2: {
        parameters: {
            query?: {
                /** @description 为 true 时清空 KPI metadata.kpi_files[].records，并对 kpi_results[].series 与 provenance.direct_cross_reference 做最多 200 点的展示抽稀；完整序列保留在规则结果文件中。 */
                exclude_records?: boolean;
            };
            header?: never;
            path: {
                task_id: components["parameters"]["TaskId"];
                rule_code: components["parameters"]["RuleCode"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 规则结果（metrics/findings） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleResultV2"];
                };
            };
            404: components["responses"]["Error404"];
        };
    };
    listKpiRecordsV2: {
        parameters: {
            query?: {
                /** @description 稳定指标 key，精确匹配。 */
                metric_key?: string;
                /** @description 任务内相对路径，精确匹配。 */
                source_file?: string;
                period_minutes?: 5 | 15 | 30 | 60;
                status?: components["schemas"]["KpiDisplayStatusV2"];
                page?: components["parameters"]["Page"];
                page_size?: components["parameters"]["KpiRecordPageSize"];
            };
            header?: never;
            path: {
                task_id: components["parameters"]["TaskId"];
                rule_code: components["parameters"]["RuleCode"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description KPI 原始记录分页 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KpiRecordPageV2"];
                };
            };
            400: components["responses"]["Error400"];
            404: components["responses"]["Error404"];
            422: components["responses"]["Error422"];
        };
    };
    getOverviewV2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 任务、注册规则、规则结果与发现问题统计 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewSummaryV2"];
                };
            };
        };
    };
    listInspectorsV2: {
        parameters: {
            query?: {
                category?: components["schemas"]["RuleCategoryV2"];
                include_hidden?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 规则元数据列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InspectorInfoV2"][];
                };
            };
        };
    };
    listDictsV2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 字典 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DictsResponseV2"];
                };
            };
        };
    };
    updateDictV2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dict_name: "province" | "operator" | "product" | "version";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DictUpdateRequestV2"];
            };
        };
        responses: {
            /** @description 更新后的字典 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DictItemV2"][];
                };
            };
            400: components["responses"]["Error400"];
        };
    };
    listKpiResourceMetricsV3: {
        parameters: {
            query?: {
                /** @description 按资源 ID、中文名或英文名模糊匹配 */
                search?: string;
                domain?: components["schemas"]["KpiResourceDomainV3"];
                include_missing?: boolean;
                page?: components["parameters"]["Page"];
                page_size?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 基础指标分页和统计 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KpiResourceMetricPageV3"];
                };
            };
            400: components["responses"]["Error400"];
            500: components["responses"]["Error500"];
        };
    };
    classifyKpiResourceMetricsV3: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KpiResourceClassificationRequestV3"];
            };
        };
        responses: {
            /** @description 整批分类成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KpiResourceClassificationResultV3"];
                };
            };
            400: components["responses"]["Error400"];
            404: components["responses"]["Error404"];
            /** @description 指标被公式、阈值或容量规则引用 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorV2"];
                };
            };
        };
    };
    listKpiClassificationAuditsV3: {
        parameters: {
            query?: {
                metric_key?: string;
                operator?: string;
                domain?: components["schemas"]["KpiResourceDomainV3"];
                page?: components["parameters"]["Page"];
                page_size?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 分类审计分页 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KpiClassificationAuditPageV3"];
                };
            };
            400: components["responses"]["Error400"];
        };
    };
    getKpiCatalogSnapshotV3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 任务 KPI 配置快照 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KpiTaskCatalogSnapshotV3"];
                };
            };
            404: components["responses"]["Error404"];
            /** @description 任务存在但 KPI 配置快照缺失 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorV2"];
                };
            };
            500: components["responses"]["Error500"];
        };
    };
}
