/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Auth Login */
        post: operations["loginV1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Auth Logout */
        post: operations["logoutV1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Auth Me */
        get: operations["getMeV1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users V1 */
        get: operations["listUsersV1"];
        put?: never;
        /** Create User V1 */
        post: operations["createUserV1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{username}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete User V1 */
        delete: operations["deleteUserV1"];
        options?: never;
        head?: never;
        /** Update User V1 */
        patch: operations["updateUserV1"];
        trace?: never;
    };
    "/api/v1/users/{username}/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Reset User Password V1 */
        put: operations["resetUserPasswordV1"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tasks V2 */
        get: operations["listTasksV2"];
        put?: never;
        /** Create Task V2 */
        post: operations["createTaskV2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Overview V2 */
        get: operations["getOverviewV2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Task V2 */
        get: operations["getTaskV2"];
        put?: never;
        post?: never;
        /** Delete Task V2 */
        delete: operations["deleteTaskV2"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/tasks/{task_id}/rerun": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rerun Task V2 */
        post: operations["rerunTaskV2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/tasks/{task_id}/rebuild": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rebuild Task V2 */
        post: operations["rebuildTaskV2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/tasks/{task_id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Report V2 */
        get: operations["getReportV2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/tasks/{task_id}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Task Logs V2 */
        get: operations["getTaskLogsV2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/tasks/{task_id}/system": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get System V2 */
        get: operations["getSystemV2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/tasks/{task_id}/rules/{rule_code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Rule Result V2 */
        get: operations["getRuleResultV2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/inspectors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Inspectors V2 */
        get: operations["listInspectorsV2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/inspector-states": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Inspector States V2
         * @description 返回普通规则启停状态分页列表。
         */
        get: operations["listInspectorStatesV2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/inspector-states/{rule_code}/enabled": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Inspector State V2
         * @description 更新一条普通规则的启停状态。
         */
        put: operations["updateInspectorStateV2"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/dicts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Dicts V2 */
        get: operations["listDictsV2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/dicts/{dict_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Dict V2 */
        put: operations["updateDictV2"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v5/kpi/measurement-units/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Kpi Measurement Units V5 */
        post: operations["importKpiMeasurementUnitsV5"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v5/kpi/measurement-units": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Kpi Measurement Units V5 */
        get: operations["listKpiMeasurementUnitsV5"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v5/kpi/measurement-units/{resource_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Set Kpi Measurement Unit Enabled V5 */
        patch: operations["setKpiMeasurementUnitEnabledV5"];
        trace?: never;
    };
    "/api/v5/kpi/measurement-bindings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Kpi Measurement Bindings V5 */
        get: operations["listKpiMeasurementBindingsV5"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v5/kpi/measurement-bindings/batch-confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Batch Confirm Kpi Measurement Bindings V5 */
        post: operations["batchConfirmKpiMeasurementBindingsV5"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v5/kpi/measurement-bindings/{binding_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Set Kpi Measurement Binding Status V5 */
        patch: operations["setKpiMeasurementBindingStatusV5"];
        trace?: never;
    };
    "/api/v5/kpi/measurement-resources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Kpi Measurement Resources V5 */
        get: operations["listKpiMeasurementResourcesV5"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v5/kpi/measurement-bindings/{binding_id}/register-metric": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register Kpi Measurement Metric V5 */
        post: operations["registerKpiMeasurementMetricV5"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v5/kpi/measurement-resources/{resource_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Kpi Measurement Resource V5 */
        patch: operations["updateKpiMeasurementResourceV5"];
        trace?: never;
    };
    "/api/v5/kpi/measurement-derived": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Kpi Measurement Derived V5 */
        post: operations["createKpiMeasurementDerivedV5"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metrics */
        get: operations["metrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_createTaskV2 */
        Body_createTaskV2: {
            /** Package File */
            package_file: string;
            /** Name */
            name?: string | null;
            /** Version */
            version?: string | null;
            /** Province */
            province?: string | null;
            /** Operator */
            operator?: string | null;
            /** Product */
            product?: string | null;
        };
        /** Body_importKpiMeasurementUnitsV5 */
        Body_importKpiMeasurementUnitsV5: {
            /** File */
            file: string;
        };
        /** DataPreparation */
        DataPreparation: {
            status: components["schemas"]["PreparationStatus"];
            /** Items */
            items: components["schemas"]["PreparationItem"][];
            /** Total */
            total: number;
            /** Success Count */
            success_count: number;
            /** Warning Count */
            warning_count: number;
            /** Failure Count */
            failure_count: number;
            /** Skip Count */
            skip_count: number;
        };
        /** DictItem */
        DictItem: {
            /** Code */
            code: string;
            /** Name */
            name: string;
        };
        /** DictUpdateRequest */
        DictUpdateRequest: {
            /** Code */
            code: string;
            /** Name */
            name: string;
        };
        /** DictsResponse */
        DictsResponse: {
            /** Province */
            province: components["schemas"]["DictItem"][];
            /** Operator */
            operator: components["schemas"]["DictItem"][];
            /** Product */
            product: components["schemas"]["DictItem"][];
            /** Version */
            version: components["schemas"]["DictItem"][];
        };
        /** Finding */
        Finding: {
            /** Finding Id */
            finding_id: string;
            /** Title */
            title: string;
            severity: components["schemas"]["Severity"];
            /** Source File */
            source_file?: string | null;
            /** Evidence */
            evidence?: string | null;
            /** Details */
            details?: string | null;
            /** Recommendation */
            recommendation?: string | null;
            /** Metrics */
            metrics?: components["schemas"]["Metric"][] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InspectionTask */
        InspectionTask: {
            /** Task Id */
            task_id: string;
            /** Name */
            name: string;
            mode: components["schemas"]["TaskMode"];
            status: components["schemas"]["TaskStatus"];
            trigger: components["schemas"]["TaskTrigger"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Completed At */
            completed_at?: string | null;
            stats: components["schemas"]["TaskStats"];
            preparation?: components["schemas"]["DataPreparation"] | null;
            system?: components["schemas"]["SystemInspection"] | null;
        };
        /** InspectorInfo */
        InspectorInfo: {
            /** Code */
            code: string;
            /** Name */
            name: string;
            category: components["schemas"]["RuleCategory"];
            severity: components["schemas"]["Severity"];
            priority: components["schemas"]["Priority"];
            /** Rule Version */
            rule_version: string;
            /**
             * Hidden
             * @default false
             */
            hidden: boolean;
            /** Description */
            description?: string | null;
            /** Recommendation */
            recommendation?: string | null;
            /** Source Patterns */
            source_patterns?: string[];
            /** Outputs */
            outputs?: {
                [key: string]: unknown;
            };
            /** Params */
            params?: {
                [key: string]: string;
            }[];
        };
        /**
         * InspectorState
         * @description 分页规则状态列表中的一条普通规则。
         */
        InspectorState: {
            /** Code */
            code: string;
            /** Name */
            name: string;
            category: components["schemas"]["RuleCategory"];
            priority: components["schemas"]["Priority"];
            /** Enabled */
            enabled: boolean;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * InspectorStateListResponse
         * @description 规则启停状态分页契约；默认每页 10 条。
         */
        InspectorStateListResponse: {
            /** Items */
            items?: components["schemas"]["InspectorState"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** KpiMeasurementBinding */
        KpiMeasurementBinding: {
            /** Id */
            id: number;
            /** Metric Resource Id */
            metric_resource_id: string | null;
            /** Measurement Unit Id */
            measurement_unit_id: string;
            /** Raw Source Name */
            raw_source_name: string;
            /** Base Source Name */
            base_source_name: string;
            /** Display Unit */
            display_unit: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "candidate" | "confirmed" | "conflict" | "ignored";
            /** Enabled */
            enabled: boolean;
            /** Task Id */
            task_id: string;
            /** Source File */
            source_file: string;
            /**
             * Metric Is Manual
             * @default false
             */
            metric_is_manual: boolean;
        };
        /** KpiMeasurementBindingBatchConfirmRequest */
        KpiMeasurementBindingBatchConfirmRequest: {
            /** Binding Ids */
            binding_ids: number[];
        };
        /** KpiMeasurementBindingBatchConfirmResponse */
        KpiMeasurementBindingBatchConfirmResponse: {
            /** Total */
            total: number;
            /** Succeeded */
            succeeded: number;
            /** Failed */
            failed: number;
            /** Items */
            items: components["schemas"]["KpiMeasurementBindingConfirmResult"][];
        };
        /** KpiMeasurementBindingConfirmResult */
        KpiMeasurementBindingConfirmResult: {
            /** Binding Id */
            binding_id: number;
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "confirmed" | "already_confirmed" | "failed";
            binding?: components["schemas"]["KpiMeasurementBinding"] | null;
            /** Error Code */
            error_code?: string | null;
            /** Message */
            message?: string | null;
        };
        /** KpiMeasurementBindingList */
        KpiMeasurementBindingList: {
            /** Total */
            total: number;
            /** Items */
            items: components["schemas"]["KpiMeasurementBinding"][];
        };
        /** KpiMeasurementBindingStatusRequest */
        KpiMeasurementBindingStatusRequest: {
            /**
             * Status
             * @enum {string}
             */
            status: "candidate" | "confirmed" | "ignored";
            /** Enabled */
            enabled?: boolean | null;
        };
        /** KpiMeasurementDerived */
        KpiMeasurementDerived: {
            /** Id */
            id: number;
            /** Measurement Unit Id */
            measurement_unit_id: string;
            /** Metric Resource Id */
            metric_resource_id: string;
            /** Numerator Metric Id */
            numerator_metric_id: string;
            /** Denominator Metric Id */
            denominator_metric_id: string;
            /**
             * Template
             * @default success_rate
             * @enum {string}
             */
            template: "success_rate" | "reverse_success_rate";
            /** Enabled */
            enabled: boolean;
        };
        /** KpiMeasurementDerivedCreateRequest */
        KpiMeasurementDerivedCreateRequest: {
            /** Measurement Unit Id */
            measurement_unit_id: string;
            /** Metric Resource Id */
            metric_resource_id: string;
            /** Numerator Metric Id */
            numerator_metric_id: string;
            /** Denominator Metric Id */
            denominator_metric_id: string;
            /**
             * Template
             * @default success_rate
             * @enum {string}
             */
            template: "success_rate" | "reverse_success_rate";
        };
        /** KpiMeasurementEnabledRequest */
        KpiMeasurementEnabledRequest: {
            /** Enabled */
            enabled: boolean;
        };
        /** KpiMeasurementImportResult */
        KpiMeasurementImportResult: {
            /** Added */
            added?: {
                [key: string]: number;
            };
            /** Updated */
            updated?: {
                [key: string]: number;
            };
            /** Skipped */
            skipped?: {
                [key: string]: unknown;
            }[];
            /** Errors */
            errors?: {
                [key: string]: unknown;
            }[];
        };
        /** KpiMeasurementMetricRegisterRequest */
        KpiMeasurementMetricRegisterRequest: {
            /** Name Zh */
            name_zh?: string | null;
            /** Name En */
            name_en?: string | null;
            /** Bind Existing Resource Id */
            bind_existing_resource_id?: string | null;
        };
        /** KpiMeasurementMetricRegisterResponse */
        KpiMeasurementMetricRegisterResponse: {
            binding: components["schemas"]["KpiMeasurementBinding"];
            metric: components["schemas"]["KpiMeasurementResource"];
        };
        /** KpiMeasurementResource */
        KpiMeasurementResource: {
            /** Resource Id */
            resource_id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "mu" | "me" | "unit";
            /** Name Zh */
            name_zh: string;
            /** Name En */
            name_en: string;
            /** Enabled */
            enabled: boolean;
            /** Is Manual */
            is_manual: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** KpiMeasurementResourceList */
        KpiMeasurementResourceList: {
            /** Total */
            total: number;
            /** Items */
            items: components["schemas"]["KpiMeasurementResource"][];
        };
        /** KpiMeasurementResourceUpdateRequest */
        KpiMeasurementResourceUpdateRequest: {
            /** Name Zh */
            name_zh?: string | null;
            /** Name En */
            name_en?: string | null;
            /** Enabled */
            enabled?: boolean | null;
        };
        /** KpiMeasurementUnit */
        KpiMeasurementUnit: {
            /** Resource Id */
            resource_id: string;
            /** Name Zh */
            name_zh: string;
            /** Name En */
            name_en: string;
            /** Filename Fragment */
            filename_fragment: string | null;
            /** Enabled */
            enabled: boolean;
            /** Metric Count */
            metric_count: number;
            /** Unit Count */
            unit_count: number;
            /** Confirmed Binding Count */
            confirmed_binding_count: number;
            /** Candidate Binding Count */
            candidate_binding_count: number;
            /** Derived Count */
            derived_count: number;
        };
        /** KpiMeasurementUnitList */
        KpiMeasurementUnitList: {
            /** Total */
            total: number;
            /** Items */
            items: components["schemas"]["KpiMeasurementUnit"][];
        };
        /** LogEntry */
        LogEntry: {
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /** Level */
            level: string;
            /** Message */
            message: string;
            /** Rule Code */
            rule_code?: string | null;
            /** Detail */
            detail?: {
                [key: string]: unknown;
            };
        };
        /** LoginRequestV1 */
        LoginRequestV1: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** LoginResponseV1 */
        LoginResponseV1: {
            /** Token */
            token: string;
            /** Username */
            username: string;
            /** Role */
            role: string;
        };
        /** Metric */
        Metric: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Value */
            value: number | string;
            /** Unit */
            unit?: string | null;
            /** Threshold */
            threshold?: {
                [key: string]: number;
            } | null;
            /** Baseline */
            baseline?: number | string | null;
            /** Series */
            series?: {
                [key: string]: unknown;
            }[] | null;
        };
        /** OverviewSummary */
        OverviewSummary: {
            /** Task Count */
            task_count: number;
            /** Registered Rule Count */
            registered_rule_count: number;
            /** Rule Result Count */
            rule_result_count: number;
            /** Finding Count */
            finding_count: number;
            status_counts: components["schemas"]["Summary"];
        };
        /** PreparationIssue */
        PreparationIssue: {
            type: components["schemas"]["PreparationIssueType"];
            /** Source */
            source?: string | null;
            /** Target */
            target?: string | null;
            /** Reason */
            reason: string;
            /** Path Length */
            path_length?: number | null;
            /** Path Limit */
            path_limit?: number | null;
        };
        /**
         * PreparationIssueType
         * @enum {string}
         */
        PreparationIssueType: "conflict" | "duplicate" | "skipped" | "failed" | "rejected";
        /** PreparationItem */
        PreparationItem: {
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Category */
            category: string;
            status: components["schemas"]["PreparationStatus"];
            /** Summary */
            summary: string;
            /** Duration Ms */
            duration_ms?: number | null;
            /** Extracted Count */
            extracted_count: number;
            /** Total Count */
            total_count: number;
            /** Issues */
            issues?: components["schemas"]["PreparationIssue"][];
        };
        /**
         * PreparationStatus
         * @enum {string}
         */
        PreparationStatus: "pass" | "warn" | "fail" | "skip" | "error";
        /**
         * Priority
         * @enum {integer}
         */
        Priority: 0 | 1 | 2;
        /**
         * RebuildMode
         * @enum {string}
         */
        RebuildMode: "full" | "incremental";
        /** RebuildRequest */
        RebuildRequest: {
            mode: components["schemas"]["RebuildMode"];
            /** Confirmed */
            confirmed: boolean;
            /** Rule Codes */
            rule_codes?: string[] | null;
            /** @default ui */
            trigger_source: components["schemas"]["RebuildTriggerSource"];
        };
        /**
         * RebuildTriggerSource
         * @enum {string}
         */
        RebuildTriggerSource: "ui" | "api";
        /** RerunRequest */
        RerunRequest: {
            /** Rule Codes */
            rule_codes?: string[] | null;
        };
        /**
         * RuleCategory
         * @enum {string}
         */
        RuleCategory: "log" | "kpi" | "traffic" | "alarm" | "config" | "resource" | "other";
        /** RuleResult */
        RuleResult: {
            /** Code */
            code: string;
            /** Name */
            name: string;
            category: components["schemas"]["RuleCategory"];
            priority: components["schemas"]["Priority"];
            /** Execution Order */
            execution_order: number;
            status: components["schemas"]["RuleStatus"];
            severity: components["schemas"]["Severity"];
            /** Summary */
            summary?: string | null;
            /** Skip Reason */
            skip_reason?: string | null;
            /** Executed At */
            executed_at?: string | null;
            /** Duration Ms */
            duration_ms?: number | null;
            /** Metrics */
            metrics?: components["schemas"]["Metric"][];
            /** Findings */
            findings?: components["schemas"]["Finding"][];
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
        };
        /**
         * RuleStateUpdateRequest
         * @description 规则启停状态更新请求。
         */
        RuleStateUpdateRequest: {
            /** Enabled */
            enabled: boolean;
        };
        /**
         * RuleStatus
         * @enum {string}
         */
        RuleStatus: "pass" | "warn" | "fail" | "error" | "skip";
        /**
         * Severity
         * @enum {string}
         */
        Severity: "low" | "medium" | "high" | "critical";
        /** Summary */
        Summary: {
            /** Total */
            total: number;
            /** Pass */
            pass: number;
            /** Warn */
            warn: number;
            /** Fail */
            fail: number;
            /** Error */
            error: number;
            /** Skip */
            skip: number;
        };
        /** SystemInspection */
        SystemInspection: {
            /** Package File */
            package_file: string;
            /** Package Checksum */
            package_checksum?: string | null;
            /** Version */
            version?: string | null;
            status: components["schemas"]["SystemStatus"];
            summary: components["schemas"]["Summary"];
            /** Rules */
            rules?: components["schemas"]["RuleResult"][];
            /** Customer */
            customer?: {
                [key: string]: string;
            };
        };
        /**
         * SystemStatus
         * @enum {string}
         */
        SystemStatus: "completed" | "failed";
        /** TaskCreated */
        TaskCreated: {
            /** Task Id */
            task_id: string;
        };
        /** TaskListResponse */
        TaskListResponse: {
            /** Items */
            items: components["schemas"]["TaskSummary"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** TaskLogs */
        TaskLogs: {
            /** Task Id */
            task_id: string;
            /** Entries */
            entries: components["schemas"]["LogEntry"][];
        };
        /**
         * TaskMode
         * @enum {string}
         */
        TaskMode: "online" | "local";
        /** TaskStats */
        TaskStats: {
            /** Total */
            total: number;
            /** Pass */
            pass: number;
            /** Warn */
            warn: number;
            /** Fail */
            fail: number;
            /** Error */
            error: number;
            /** Skip */
            skip: number;
            /**
             * Systems
             * @default 1
             */
            systems: number;
        };
        /**
         * TaskStatus
         * @enum {string}
         */
        TaskStatus: "pending" | "running" | "completed" | "failed";
        /** TaskSummary */
        TaskSummary: {
            /** Task Id */
            task_id: string;
            /** Name */
            name: string;
            mode: components["schemas"]["TaskMode"];
            status: components["schemas"]["TaskStatus"];
            trigger: components["schemas"]["TaskTrigger"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Completed At */
            completed_at?: string | null;
            stats: components["schemas"]["TaskStats"];
            preparation?: components["schemas"]["DataPreparation"] | null;
            system?: components["schemas"]["SystemInspection"] | null;
            /** Customer Province */
            customer_province?: string | null;
            /** Customer Operator */
            customer_operator?: string | null;
            /** Customer Product */
            customer_product?: string | null;
            /** Customer Version */
            customer_version?: string | null;
        };
        /**
         * TaskTrigger
         * @enum {string}
         */
        TaskTrigger: "api" | "cli" | "rerun";
        /** UserCreateRequestV1 */
        UserCreateRequestV1: {
            /** Username */
            username: string;
            /** Password */
            password: string;
            /**
             * Role
             * @enum {string}
             */
            role: "admin" | "viewer";
        };
        /** UserInfoV1 */
        UserInfoV1: {
            /** Username */
            username: string;
            /** Role */
            role: string;
        };
        /** UserListResponseV1 */
        UserListResponseV1: {
            /** Items */
            items?: components["schemas"]["UserV1"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** UserPasswordRequestV1 */
        UserPasswordRequestV1: {
            /** New Password */
            new_password: string;
        };
        /** UserRoleRequestV1 */
        UserRoleRequestV1: {
            /**
             * Role
             * @enum {string}
             */
            role: "admin" | "viewer";
        };
        /** UserV1 */
        UserV1: {
            /** Username */
            username: string;
            /** Role */
            role: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    loginV1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequestV1"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponseV1"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logoutV1: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getMeV1: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserInfoV1"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listUsersV1: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserListResponseV1"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    createUserV1: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreateRequestV1"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserV1"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deleteUserV1: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    updateUserV1: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserRoleRequestV1"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserV1"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resetUserPasswordV1: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserPasswordRequestV1"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserV1"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listTasksV2: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    createTaskV2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_createTaskV2"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getOverviewV2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewSummary"];
                };
            };
        };
    };
    getTaskV2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InspectionTask"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deleteTaskV2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rerunTaskV2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RerunRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rebuildTaskV2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RebuildRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getReportV2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getTaskLogsV2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskLogs"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getSystemV2: {
        parameters: {
            query?: {
                exclude_details?: boolean;
            };
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemInspection"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getRuleResultV2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
                rule_code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listInspectorsV2: {
        parameters: {
            query?: {
                category?: string | null;
                include_hidden?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InspectorInfo"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listInspectorStatesV2: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                category?: string | null;
                enabled?: boolean | null;
                search?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InspectorStateListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    updateInspectorStateV2: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                rule_code: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RuleStateUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InspectorState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listDictsV2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DictsResponse"];
                };
            };
        };
    };
    updateDictV2: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                dict_name: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["DictUpdateRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DictItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    importKpiMeasurementUnitsV5: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_importKpiMeasurementUnitsV5"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KpiMeasurementImportResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listKpiMeasurementUnitsV5: {
        parameters: {
            query?: {
                search?: string | null;
                enabled?: boolean | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KpiMeasurementUnitList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    setKpiMeasurementUnitEnabledV5: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                resource_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["KpiMeasurementEnabledRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listKpiMeasurementBindingsV5: {
        parameters: {
            query?: {
                measurement_unit_id?: string | null;
                /** @description 按测量单元资源 ID、中文名或英文名模糊过滤绑定关系。 */
                unit_search?: string | null;
                status?: string | null;
                search?: string | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KpiMeasurementBindingList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    batchConfirmKpiMeasurementBindingsV5: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KpiMeasurementBindingBatchConfirmRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KpiMeasurementBindingBatchConfirmResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    setKpiMeasurementBindingStatusV5: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                binding_id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["KpiMeasurementBindingStatusRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listKpiMeasurementResourcesV5: {
        parameters: {
            query?: {
                kind?: string | null;
                search?: string | null;
                enabled?: boolean | null;
                page?: number;
                page_size?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KpiMeasurementResourceList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    registerKpiMeasurementMetricV5: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                binding_id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["KpiMeasurementMetricRegisterRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KpiMeasurementMetricRegisterResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    updateKpiMeasurementResourceV5: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                resource_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["KpiMeasurementResourceUpdateRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KpiMeasurementResource"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    createKpiMeasurementDerivedV5: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["KpiMeasurementDerivedCreateRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KpiMeasurementDerived"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    metrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
