/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 健康检查 */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Prometheus 指标（内部可观测） */
        get: operations["metrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 任务列表 */
        get: operations["listTasks"];
        put?: never;
        /** 创建巡检任务（一个压缩包 = 一个任务） */
        post: operations["createTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 任务摘要（不含全量规则结果） */
        get: operations["getTask"];
        put?: never;
        post?: never;
        /** 删除任务（级联删除 uploads/ 与 output/ 现场数据） */
        delete: operations["deleteTask"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/rerun": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 增量重跑（全部或指定规则） */
        post: operations["rerunTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 巡检报告（HTML 在线预览） */
        get: operations["getReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 任务执行日志 */
        get: operations["getTaskLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/system": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 系统摘要与规则状态列表 */
        get: operations["getSystem"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/rules/{rule_code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 单规则完整结果 */
        get: operations["getRuleResult"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inspectors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 已注册规则元数据（只读） */
        get: operations["listInspectors"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dicts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 全部预制数据字典 */
        get: operations["listDicts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dicts/{dict_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 维护字典项（纯内部开放） */
        put: operations["updateDict"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        TaskStatus: "pending" | "running" | "completed" | "failed";
        /** @enum {string} */
        RuleStatus: "pass" | "warn" | "fail" | "error" | "skip";
        /** @enum {string} */
        Severity: "low" | "medium" | "high" | "critical";
        /**
         * @description P0 数据准备 / P1 基础检查 / P2 综合分析
         * @enum {integer}
         */
        Priority: 0 | 1 | 2;
        /** @enum {string} */
        RuleCategory: "log" | "kpi" | "traffic" | "alarm" | "config" | "resource" | "other";
        /** @enum {string} */
        TaskMode: "online" | "local";
        /** @enum {string} */
        TaskTrigger: "api" | "cli" | "rerun";
        Summary: {
            total: number;
            pass: number;
            warn: number;
            fail: number;
            error: number;
            skip: number;
        };
        TaskStats: components["schemas"]["Summary"] & {
            systems?: number;
        };
        Metric: {
            /** @description 契约级稳定标识，跨任务/系统不可变 */
            key: string;
            label: string;
            value: number | string;
            unit?: string;
            threshold?: {
                min?: number;
                max?: number;
            };
            baseline?: number | string;
            /** @description 趋势图数据 */
            series?: {
                /** @description 时间点或序号 */
                t?: string;
                v?: number | string;
            }[];
        };
        Finding: {
            finding_id: string;
            title: string;
            severity: components["schemas"]["Severity"];
            /** @description 结论来源文件（可定位原始数据） */
            source_file?: string;
            /** @description 证据片段（默认截断 2KB） */
            evidence?: string;
            details?: string;
            recommendation?: string;
            metrics?: components["schemas"]["Metric"][];
        };
        RuleResult: {
            code: string;
            name: string;
            category: components["schemas"]["RuleCategory"];
            priority: components["schemas"]["Priority"];
            /** @description 消费的中间产物 key（执行器据此推导依赖） */
            inputs?: string[];
            execution_order: number;
            status: components["schemas"]["RuleStatus"];
            severity: components["schemas"]["Severity"];
            summary?: string;
            /** @description status=skip 时必填 */
            skip_reason?: string;
            /** Format: date-time */
            executed_at?: string;
            duration_ms?: number;
            metrics?: components["schemas"]["Metric"][];
            findings?: components["schemas"]["Finding"][];
            /** @description 产出的中间产物 key（供下游消费） */
            artifacts?: string[];
            metadata?: {
                [key: string]: unknown;
            };
        };
        SystemInspection: {
            system_id: string;
            system_name?: string;
            package_file: string;
            package_checksum?: string;
            version?: string;
            /** @enum {string} */
            status: "completed" | "failed";
            summary: components["schemas"]["Summary"];
            rules: components["schemas"]["RuleResult"][];
            customer?: {
                [key: string]: unknown;
            };
        };
        InspectionTask: {
            task_id: string;
            name: string;
            mode: components["schemas"]["TaskMode"];
            status: components["schemas"]["TaskStatus"];
            trigger: components["schemas"]["TaskTrigger"];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            completed_at?: string;
            stats: components["schemas"]["TaskStats"];
            system?: components["schemas"]["SystemInspection"];
        };
        TaskCreated: {
            task_id: string;
        };
        TaskSummary: components["schemas"]["InspectionTask"] & {
            system?: unknown;
        };
        TaskListResponse: {
            items: components["schemas"]["TaskSummary"][];
            total: number;
            page: number;
            page_size: number;
        };
        RerunRequest: {
            /** @description 不填表示重跑该任务全部规则 */
            rule_codes?: string[];
        };
        LogEntry: {
            /** Format: date-time */
            ts: string;
            level: string;
            message: string;
            rule_code?: string;
            detail?: {
                [key: string]: unknown;
            };
        };
        TaskLogs: {
            task_id: string;
            entries: components["schemas"]["LogEntry"][];
        };
        InspectorInfo: {
            code: string;
            name: string;
            category: components["schemas"]["RuleCategory"];
            severity: components["schemas"]["Severity"];
            priority: components["schemas"]["Priority"];
            rule_version: string;
            hidden: boolean;
            description?: string;
            recommendation?: string;
            inputs: string[];
            outputs: {
                metrics?: {
                    key?: string;
                    label?: string;
                    unit?: string;
                    /** @enum {string} */
                    type?: "number" | "string" | "trend";
                }[];
                artifacts?: string[];
            };
            params?: {
                key?: string;
                label?: string;
                default?: string;
            }[];
        };
        DictItem: {
            /** @description 编码，仅小写字母/数字/下划线 */
            code: string;
            name: string;
        };
        DictsResponse: {
            province: components["schemas"]["DictItem"][];
            operator: components["schemas"]["DictItem"][];
            product: components["schemas"]["DictItem"][];
            version: components["schemas"]["DictItem"][];
        };
        DictUpdateRequest: {
            code: string;
            name: string;
        };
        Error: {
            /**
             * @description 错误码（新增时同步契约与实现）
             * @enum {string}
             */
            code: "invalid_package" | "package_too_large" | "invalid_dict" | "bad_request" | "unknown_rule" | "not_found" | "internal";
            message: string;
            detail?: {
                [key: string]: unknown;
            };
        };
    };
    responses: {
        /** @description 请求错误 */
        Error400: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 资源不存在 */
        Error404: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 文件过大 */
        Error413: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        TaskId: string;
        RuleCode: string;
        Page: number;
        PageSize: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 服务健康 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    metrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Prometheus 文本格式指标 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    listTasks: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                page_size?: components["parameters"]["PageSize"];
                status?: components["schemas"]["TaskStatus"];
                system_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 任务摘要列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskListResponse"];
                };
            };
        };
    };
    createTask: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description 数据压缩包（zip/tar.gz，默认上限 2GB）
                     */
                    package_file: string;
                    /** @description 任务名称（可选） */
                    name?: string;
                    /** @description 版本字典编码（可选） */
                    version?: string;
                    /** @description 省份字典编码（可选） */
                    province?: string;
                    /** @description 运营商字典编码（可选） */
                    operator?: string;
                    /**
                     * @description 已存在同包任务时是否删除旧任务并重新创建
                     * @default false
                     */
                    force?: boolean;
                };
            };
        };
        responses: {
            /** @description 任务已创建，异步执行 */
            202: {
                headers: {
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskCreated"];
                };
            };
            400: components["responses"]["Error400"];
            /** @description 已存在相同包的任务 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            413: components["responses"]["Error413"];
        };
    };
    getTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 任务摘要 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InspectionTask"];
                };
            };
            404: components["responses"]["Error404"];
        };
    };
    deleteTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已删除 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["Error404"];
        };
    };
    rerunTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RerunRequest"];
            };
        };
        responses: {
            /** @description 重跑任务已受理 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskCreated"];
                };
            };
            404: components["responses"]["Error404"];
        };
    };
    getReport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description HTML 报告 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
            404: components["responses"]["Error404"];
        };
    };
    getTaskLogs: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 结构化执行日志 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskLogs"];
                };
            };
            404: components["responses"]["Error404"];
        };
    };
    getSystem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 系统巡检结果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemInspection"];
                };
            };
            404: components["responses"]["Error404"];
        };
    };
    getRuleResult: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: components["parameters"]["TaskId"];
                rule_code: components["parameters"]["RuleCode"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 规则结果（metrics/findings/artifacts） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleResult"];
                };
            };
            404: components["responses"]["Error404"];
        };
    };
    listInspectors: {
        parameters: {
            query?: {
                category?: components["schemas"]["RuleCategory"];
                include_hidden?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 规则元数据列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InspectorInfo"][];
                };
            };
        };
    };
    listDicts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 字典 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DictsResponse"];
                };
            };
        };
    };
    updateDict: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dict_name: "province" | "operator" | "product" | "version";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DictUpdateRequest"];
            };
        };
        responses: {
            /** @description 更新后的字典 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DictItem"][];
                };
            };
            400: components["responses"]["Error400"];
        };
    };
}
